import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";

// fonts
const IranYekan = localFont({
  src: [
    {
      path: "../assets/fonts/IRANYekanX-Regular.woff2",
    },
    {
      path: "../assets/fonts/IRANYekanXVF.ttf",
    },
    {
      path: "../assets/fonts/webfont.woff",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${IranYekan.className}} antialiased border`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
